configuration: Release
init:
  - git config --global core.autocrlf true
before_build:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore
build_script:
  - msbuild "DesignPatterns.sln" /verbosity:minimal
after_build:
  - ps: Write-Host "build DONE,Start UnitTest"
  - ps: Write-Host "当前目录下的文件："
  - cmd: dir /a *
  - cmd: cd C:/projects/DesignPatterns/SimpleFactory/bin
  - cmd: dir /a *
  - cmd: cd C:/projects/DesignPatterns/SimpleFactoryTests/bin/Release
  - cmd: dir /a *
  # - xunit.console.clr4 C:/projects/DesignPatterns/SimpleFactoryTests/bin/Release/SimpleFactoryTests.dll /appveyor
clone_depth: 1
test:
  assemblies:
  - SimpleFactoryTests.dll
  - StrategyPatternTests.dll
deploy: off
